version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - detector
  detector:
    build:
      context: ./ai-detector
      dockerfile: ../docker/Dockerfile.detector
    expose:
      - "9000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
